import setuptools
from distutils.core import setup

setup(name='pyDAG3',
      version='3.5.5',
      author='Dave Gutz',
      author_email='davegutz@alum.mit.edu',
      url='http://www.google.com',
      description='First Release Dave Gutz Python 3 port (need to try Linux).  Iterators for InFile and StringSet',
      long_description=None,
      license=None,
      platforms='OS Independent',
      classifiers=[
          'Development Status :: 4 - Beta',
          'Environment :: Console',
          'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
          'Intended Audience :: Developers',
          'Operating System :: OS Independent',
          'Programming Language :: Python',
          'Topic :: Utilities'
      ],
      package_dir={'pyDAG3': 'pyDAG3'},
      package_data={'pyDAG3':
                    ['Apps/RotorDynamicModel/README.TXT',
                     'Apps/RotorDynamicModel/rotorCurves.txt',
                     'Apps/RotorDynamicModel/rotorCurves.txtOld',
                     'Apps/RotorDynamicModel/rotorModel.csv',
                     'Apps/RotorDynamicModel/rotorModel.dat',
                     'Apps/RotorDynamicModel/rotorModel.map',
                     'Apps/RotorDynamicModel/rotorModel.xls',
                     'Apps/RotorDynamicModel/rotorModel006.xls',
                     'Apps/RotorDynamicModel/rotorModel010.xls',
                     'Apps/RotorDynamicModel/rotorModel012.xls',
                     'Apps/RotorDynamicModel/rotorModel_2damstep.csv',
                     'Apps/RotorDynamicModel/rotorModel_2damstep.xls',
                     'Apps/genGorilla/README.TXT',
                     'Apps/genGorilla/airstart.mtc',
                     'Apps/genGorilla/g1000.def',
                     'Apps/genGorilla/g1000.int',
                     'Apps/genGorilla/g110.def',
                     'Apps/genGorilla/g110.int',
                     'Apps/genGorilla/g110.mtp',
                     'Apps/genGorilla/g110.scd',
                     'Apps/genGorilla/g111.def',
                     'Apps/genGorilla/g111.int',
                     'Apps/genGorilla/g111.mtp',
                     'Apps/genGorilla/g111.scd',
                     'Apps/genGorilla/genGorilla.dic',
                     'Apps/makeCMD/makeCMD.dic',
                     'Apps/RotorDynamicModel/rotorModel.dic',
                     'Apps/watermark/README.txt',
                     'Apps/watermark/watermarkKPE.png',
                     'Apps/watermark/watermarkKPEr.png',
                     'Apps/watermark/Figure_1.jpg',
                     'Apps/watermark/Figure_1.png',
                     'Apps/watermark/watermark.dic',
                     'pyDAG3.dic',
                     'System/tests/MANIFEST.in',
                     'System/tests/mySystem.dic',
                     'System/tests/pyDAG3.dic']},
      scripts=['pyDAG3/Apps/RotorDynamicModel/rotorModel.py',
               'pyDAG3/Apps/makeCMD/makeTBLADJ',
               'pyDAG3/Apps/makeCMD/map2tbl',
               'pyDAG3/Apps/makeCMD/ins2adj',
               'pyDAG3/Apps/makeCMD/sar2trim',
               'pyDAG3/Apps/genGorilla/genGorilla.py',
               'pyDAG3/Apps/makeCMD/makeCMD.py',
               'pyDAG3/Apps/makeCMD/makeTBLADJ.py',
               'pyDAG3/Apps/makeCMD/ctblmkr_GEneric.c',
               'pyDAG3/Apps/watermark/watermark.py',
               'pyDAG3/System/pyReplace.py'],
      packages=['pyDAG3', 'pyDAG3.TextProcessing', 'pyDAG3.Dynamics', 'pyDAG3.Tables', 'pyDAG3.System',
                'pyDAG3.Tkinter', 'pyDAG3.Control', 'pyDAG3.Control.Servo'],
      install_requires=['Pillow', 'twine', 'wheel', 'pip', 'setuptools', 'control', 'numpy',
                        'matplotlib', 'scilab2py']
      )
